export const widgetTextEditData = [
    { id: "widget1", },
    { id: "widget2", },
    { id: "widget4", },
    { id: "widget5", },
    { id: "widget3", },
    { id: "widget6", },
    { id: "widget7", },
    { id: "widget8", },
    { id: "widget9", },
    { id: "widget10", },
    { id: "widget11", },
    { id: "widget12", },
    { id: "widget13", },
    { id: "widget14", },
    { id: "widget15", },
    { id: "widget16", },
    { id: "widget17", },
    { id: "widget18", },
    { id: "widget19", },
    { id: "widget20", },
    { id: "widget21", },
    { id: "widget22", },
    { id: "widget23", },
    { id: "widget24", },
];