export const widgetData = [
    // { id: "widget1", type: "calander", size: "1x1", label: "캘린더" },
    // { id: "widget2", type: "calander", size: "2x1", label: "캘린더" },
    // { id: "widget3", type: "calander", size: "3x1", label: "캘린더" },
    // { id: "widget4", type: "weather", size: "1x1", label: "날씨" },
    // { id: "widget5", type: "weather", size: "2x1", label: "날씨" },
    // { id: "widget6", type: "weather", size: "3x1", label: "날씨" },
    { id: "widget7", type: "memo", size: "1x1", label: "메모" },
    { id: "widget8", type: "memo", size: "2x1", label: "메모" },
    { id: "widget9", type: "memo", size: "3x1", label: "메모" },
    { id: "widget10", type: "info", size: "1x1", label: "소개" },
    { id: "widget11", type: "info", size: "2x1", label: "소개" },
    { id: "widget12", type: "info", size: "3x1", label: "소개" },
    // { id: "widget13", type: "bookmark", size: "1x1", label: "북마크" },
    // { id: "widget14", type: "bookmark", size: "2x1", label: "북마크" },
    // { id: "widget15", type: "bookmark", size: "3x1", label: "북마크" },
    { id: "widget16", type: "display", size: "1x1", label: "전시대" },
    { id: "widget17", type: "display", size: "2x1", label: "전시대" },
    { id: "widget18", type: "display", size: "3x1", label: "전시대" },
    { id: "widget19", type: "image", size: "1x1", label: "이미지" },
    { id: "widget20", type: "image", size: "2x1", label: "이미지" },
    { id: "widget21", type: "image", size: "3x1", label: "이미지" },
    // { id: "widget22", type: "countdown", size: "1x1", label: "카운트다운" },
    // { id: "widget23", type: "countdown", size: "2x1", label: "카운트다운" },
    // { id: "widget24", type: "countdown", size: "3x1", label: "카운트다운" },
];